### ISSUE TITLE
Can you add turkish language at DeepL Translator for webpage?

### ISSUE THREAD

**Issue by skream27** [fastaddons/WebTranslate#11]
Can you add turkish language at DeepL Translator for webpage translate?

**Comment by fastaddons** [comment]
Sure thing! 
Thanks for letting me know! I see they've added also few other new languages.
I will try to release today or tomorrow.

**Comment by fastaddons** [comment]
Fixed in 4.3, already released for Thunderbird, Chrome version is being reviewed (so usually up to 24h).
