### ISSUE TITLE
deepl did not work in thunderbird 102.13.0 (Ubuntu 22.04.2 LTS) anymore

### ISSUE THREAD

**Issue by MarkyMarkDE** [fastaddons/WebTranslate#14]
Unfortunately deepl in thunderbird did not work anymore. I test it with another TB Addon for deepl, same Problem. The Firefox Addon for deepl works, what exact the problem is, don't know. When I change in your addon the translator to google, all works but not deepl (deepl window stays blank) ...

Sorry for this cross posting, it should explain more detailed.
[DeepL-Selected-Text Issue #6](https://github.com/itagagaki/DeepL-Selected-Text/issues/6)

Please read this: https://addons.mozilla.org/en-US/firefox/addon/to-deepl/reviews/
Seems that the API of deepl is since longer time broken (round before 6 months), "To DeepL translation" Addon for firefox was also affect and solved this problem.

**Comment by Juraj-Masiar** [comment]
Hello,
Could you make a screenshot of the window with the broken translator?
I've tested it now and it seems to be working fine in Firefox, Thunderbird and Thunderbird Nightly.
I'm not using any API, it only loads the whole page into the iframe so it should stay working even when they change stuff.

**Comment by MarkyMarkDE** [comment]
> Hello, Could you make a screenshot of the window with the broken translator? I've tested it now and it seems to be working fine in Firefox, Thunderbird and Thunderbird Nightly. I'm not using any API, it only loads the whole page into the iframe so it should stay working even when they change stuff.

on Ubuntu nothing worked, I select a text and select it to translate but the window which pushed up stays blank. What for Screenshot? Of an Empty Window (empty means without the selected text to translate)?

**Comment by Juraj-Masiar** [comment]
There is many ways for the window to be "empty" :), I just to be sure I understand the issue. Also color of the "empty" may be handy too! 
As the saying goes, "a picture is worth 1000 words" :)

**Comment by MarkyMarkDE** [comment]
> There is many ways for the window to be "empty" :), I just to be sure I understand the issue. Also color of the "empty" may be handy too! As the saying goes, "a picture is worth 1000 words" :)

![Bildschirmfoto vom 2023-07-08 22-36-42](https://github.com/fastaddons/WebTranslate/assets/12845477/4635532b-b2cc-49be-90ad-f00eb8c69546)

This comes in error console:

22:36:25.413 Laden fehlgeschlagen für das <script> mit der Quelle "moz-extension://0cd6b4e1-e707-456c-97ab-c0792bd40319/browser-polyfill.min.js". editor.html:8:1
22:36:26.051 Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 4
22:36:26.051 Das Cookie "rgReload" wurde abgelehnt, da es bereits abgelaufen ist. translator
22:36:26.051 Das Cookie "dapUid" wurde abgelehnt, da es bereits abgelaufen ist. translator
22:36:26.815 DeepL Translator <empty string> translator_late.min.$4e2dab.js:44:844589
22:36:27.121 Welcome to DeepL.com! translator_late.min.$4e2dab.js:44:200277
22:36:27.129 TypeError: r is null translator_late.min.$4e2dab.js:44:688844
22:36:27.165 Module already defined 'LMT_UI_SystemNotification' translator_early.min.$333b01.js:1:421
22:36:27.176 Module already defined 'FeatureManager' translator_early.min.$333b01.js:1:421
22:36:27.177 [FeatureManager.defineType] /translator/core/selectLangUI is already defined! utils.chunk.$1a79bf.js:1:7900
22:36:31.848 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/speakSourceText" utils.chunk.$1a79bf.js:1:6450
22:36:31.850 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/speakTargetText" utils.chunk.$1a79bf.js:1:6450
22:36:31.851 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/sendTranslationState" utils.chunk.$1a79bf.js:1:6450
22:36:31.855 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality/core" utils.chunk.$1a79bf.js:1:6450
22:36:31.856 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality/ad" utils.chunk.$1a79bf.js:1:6450
22:36:31.856 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality/adUi" utils.chunk.$1a79bf.js:1:6450
22:36:31.856 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality" utils.chunk.$1a79bf.js:1:6450
22:36:31.901 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/observeTextSession" utils.chunk.$1a79bf.js:1:6450
22:36:31.909 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/analytics" utils.chunk.$1a79bf.js:1:6450
22:36:31.909 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/web/analytics" utils.chunk.$1a79bf.js:1:6450
22:36:31.910 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/shareTargetText" utils.chunk.$1a79bf.js:1:6450
22:36:32.274 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/manyTranslationsNag" utils.chunk.$1a79bf.js:1:6450
22:36:32.275 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/web/manyTranslationsUi" utils.chunk.$1a79bf.js:1:6450
22:36:52.974 sendRemoveListener on closed conduit admin@fastaddons.com_WebTranslate.2061584305933 3 ConduitsChild.jsm:112
22:36:57.061 Laden fehlgeschlagen für das <script> mit der Quelle "moz-extension://0cd6b4e1-e707-456c-97ab-c0792bd40319/browser-polyfill.min.js". editor.html:8:1
22:36:57.502 Das Cookie "rgReload" wurde abgelehnt, da es bereits abgelaufen ist. translator
22:36:57.502 Das Cookie "dapUid" wurde abgelehnt, da es bereits abgelaufen ist. translator
22:36:58.346 DeepL Translator <empty string> translator_late.min.$4e2dab.js:44:844589
22:36:58.649 TypeError: r is null translator_late.min.$4e2dab.js:44:688844
22:36:58.652 Welcome to DeepL.com! translator_late.min.$4e2dab.js:44:200277
22:36:58.716 Module already defined 'FeatureManager' translator_early.min.$333b01.js:1:421
22:36:58.731 Module already defined 'LMT_UI_SystemNotification' translator_early.min.$333b01.js:1:421
22:36:58.746 [FeatureManager.defineType] /translator/core/selectLangUI is already defined! utils.chunk.$1a79bf.js:1:7900
22:37:03.373 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/speakSourceText" utils.chunk.$1a79bf.js:1:6450
22:37:03.375 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/speakTargetText" utils.chunk.$1a79bf.js:1:6450
22:37:03.375 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/sendTranslationState" utils.chunk.$1a79bf.js:1:6450
22:37:03.385 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality/core" utils.chunk.$1a79bf.js:1:6450
22:37:03.385 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality/ad" utils.chunk.$1a79bf.js:1:6450
22:37:03.385 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality/adUi" utils.chunk.$1a79bf.js:1:6450
22:37:03.385 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/formality" utils.chunk.$1a79bf.js:1:6450
22:37:03.430 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/observeTextSession" utils.chunk.$1a79bf.js:1:6450
22:37:03.436 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/analytics" utils.chunk.$1a79bf.js:1:6450
22:37:03.436 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/web/analytics" utils.chunk.$1a79bf.js:1:6450
22:37:03.437 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/shareTargetText" utils.chunk.$1a79bf.js:1:6450
22:37:03.841 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/common/manyTranslationsNag" utils.chunk.$1a79bf.js:1:6450
22:37:03.842 [FeatureManager] Required features could not be resolved within 5000ms 
Required: <unavailable> 
Missing: <unavailable> 
Required by: "/translator/web/manyTranslationsUi" utils.chunk.$1a79bf.js:1:6450
22:37:05.601 sendRemoveListener on closed conduit admin@fastaddons.com_WebTranslate.2061584305980 3 ConduitsChild.jsm:112

**Comment by Juraj-Masiar** [comment]
Wait a second, so the translator works but only the selected word is not "inserted", right?

**Comment by MarkyMarkDE** [comment]
> Wait a second, so the translator works but only the selected word is not "inserted", right?

yes, but this happens only with deepl, Google is fine

**Comment by Juraj-Masiar** [comment]
I see now, I can reproduce it here too! Which is great!
I'll try fix it in the morning and release it afterwards, it should be easy.
Thank you for reporting this and good night :)

**Comment by MarkyMarkDE** [comment]
> I see now, I can reproduce it here too! Which is great! I'll try fix it in the morning and release it afterwards, it should be easy. Thank you for reporting this and good night :)

THANK YOU SO MUCH! SLEEPING GOOD WELL :wink:

**Comment by Juraj-Masiar** [comment]
New version 4.8 has just been released.... but as I'm testing it now on my personal PC, it didn't helped :(
Which is pretty interesting because it worked in my testing Thunderbird. Something fishy is happening, I'll have to investigate it more deeply, but most likely again tomorrow when I get to work.

**Comment by MarkyMarkDE** [comment]
funny, in Firefox deepl work but check this out please => error console Firefox 102.13.0esr on Ubuntu 22.04.2 LTS (Wayland):

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
sendRemoveListener on closed conduit admin@fastaddons.com_WebTranslate.412316890983 3 ConduitsChild.jsm:112
sendRemoveListener on closed conduit languagetool-webextension@languagetool.org.27075473833985 3 ConduitsChild.jsm:112

![Bildschirmfoto vom 2023-07-09 15-40-19](https://github.com/fastaddons/WebTranslate/assets/12845477/d411c79e-085f-4313-a742-8497f4c52234)

**Comment by MarkyMarkDE** [comment]
> New version 4.8 has just been released.... but as I'm testing it now on my personal PC, it didn't helped :( Which is pretty interesting because it worked in my testing Thunderbird. Something fishy is happening, I'll have to investigate it more deeply, but most likely again tomorrow when I get to work.

Yes, in Thunderbird lot of functions change in every new Versions, as you know maybe, the next mayor release is complete new (SuperNova UI). Is okay, it would be great, if you find the Problem and be able to solve. The Translations of deepl are much better in quality as from google :wink:

**Comment by MarkyMarkDE** [comment]
> New version 4.8 has just been released.... but as I'm testing it now on my personal PC, it didn't helped :( Which is pretty interesting because it worked in my testing Thunderbird. Something fishy is happening, I'll have to investigate it more deeply, but most likely again tomorrow when I get to work.

I have tested a little bit in Thunderbird and this is what I have probably seen:

The Addon tries to load in first place the marked Text and Translation quite well, but in the last Moment it loads a complete blank window.

**Comment by Juraj-Masiar** [comment]
From what I can see, this is indeed something special in the DeepL page.
Even if I just let my addon to create new tab in Thunderbird with page:
https://www.deepl.com/translator#en/sk/Hello!
It will open it without entered text.

I see what I can do, there are some workarounds I can try...

**Comment by MarkyMarkDE** [comment]
> From what I can see, this is indeed something special in the DeepL page. Even if I just let my addon to create new tab in Thunderbird with page: https://www.deepl.com/translator#en/sk/Hello! It will open it without entered text.
> 
> I see what I can do, there are some workarounds I can try...

Thank you so much. Hopefully you find a workaround.

**Comment by MarkyMarkDE** [comment]
> No luck on Monday :(, I've tried to fake "user-agent" to appear as a browser, but it didn't helped. I guess they are using some new API that have not been yet implemented in the Thunderbird.
> 
> The good news is, if I'm seeing it right, the new Thunderbird 115 will fix the issue. And the rollout of 115 should start already tomorrow: https://www.thunderbird.net/en-US/thunderbird/115.0/releasenotes/ So see you tomorrow :)

yesterday I got an update of Thunderbird but unfortunately not 115.* it stays here in 102.13.0

**Comment by Juraj-Masiar** [comment]
Hello again,
I'm sorry for the delay, I've visited dentist on Tuesday and I can tell you that without 2 wisdom teeth it's pretty hard to think straight :(

In any case, I'm back and ready to fix this.
I've just tried to upgrade to 115 but it didn't helped, which is super bad. But I have some other ideas so I'll try it now.

**Comment by MarkyMarkDE** [comment]
> Hello again, I'm sorry for the delay, I've visited dentist on Tuesday and I can tell you that without 2 wisdom teeth it's pretty hard to think straight :(
> 
> In any case, I'm back and ready to fix this. I've just tried to upgrade to 115 but it didn't helped, which is super bad. But I have some other ideas so I'll try it now.

is okay, no worries. I know, the last month I lost all my teeths - really funny I can say ... :wink:

**Comment by samantarya** [comment]
Have been having the same problem since last week. Just wanted to repeat it here. It works with Google Translate but not with DeepL. Btw @MarkyMarkDE how can I see the console output for things in Thunderbird? 
App Versions - Thunderbird: 102.13.0, Kubuntu 22.04.02 LTS, Web Transalte 4.8

**Comment by MarkyMarkDE** [comment]
quite simple.
Extras ==> Developer Tools ==> Error Console.
Hope you find it, this is my English Translation and not Thunderbird's own, I have the German Thunderbird  :wink:

**Comment by Juraj-Masiar** [comment]
DONE!!!
Finally, I'm so tired, it took me whole day to build a workaround for this crap :(
I can't tell why it started to fail, something has changed on the DeepL page that somehow breaks only in Thunderbird, no matter what I do, and I tried everything.
After it all failed, I've build a workaround that places the selected text manually inside the box, so that should fix it once and for all.

New version 4.9 is already released so just click Check for updates in the addons page or wait till Thunderbird auto-updates it.
Please let me know if anything breaks again and have a nice weekend! :)

**Comment by MarkyMarkDE** [comment]
> DONE!!! Finally, I'm so tired, it took me whole day to build a workaround for this crap :( I can't tell why it started to fail, something has changed on the DeepL page that somehow breaks only in Thunderbird, no matter what I do, and I tried everything. After it all failed, I've build a workaround that places the selected text manually inside the box, so that should fix it once and for all.
> 
> New version 4.9 is already released so just click Check for updates in the addons page or wait till Thunderbird auto-updates it. Please let me know if anything breaks again and have a nice weekend! :)

just a suggestion for improvement: purely for reasons of standardization, I would now include this special change for deepl for all translation services (in the Addon for Firefox and Thunderbird), then you also have much more control over the data that is passed to the translator. I remember special cases where the text was not "cleaned" correctly and then the tool also remained empty and you got no translation.

**Comment by Juraj-Masiar** [comment]
Those are errors in the Thunderbird / Firefox code. Not all errors means an issue, although it's a bad practice to see them in a normal console log if everything works as expected.
In general, all files that have "resource://" prefix are internal browser files.
And all files that comes from one of the extensions have "moz-extension://" prefix.

Regarding the last error - I can't tell, but again, it's internal error, although the "languagetool-mailextension@languagetool.org" looks like an extension, but I don't see any extension files mentioned in the log.
BTW, if you are pasting code or logs, it's best to put triple backticks (```) before / after the code.

**Comment by MarkyMarkDE** [comment]
> 

okay, i have paste the Code with "Add Code" Function from GitHub.
Next i will Add tree backticks :wink:

**Comment by Juraj-Masiar** [comment]
Sorry I should have been more specific, the triple backticks needs to be placed "on the line above and on the line below the code" :).

The target language is a bit complicated thing - each language provider can use different "language code", that's why it didn't worked well when switching between providers. 
But in the new version I've updated the DeepL language support (which added some new languages) and they seems to be using different format now, more compatible with other translators, that's why it works now.

But yeah, there are some annoying things about my translator that needs fixing, but usually I have too much work with my other addons, mostly my big speed dial (that actually pays for all my other addons).

**Comment by MarkyMarkDE** [comment]
> Sorry I should have been more specific, the triple backticks needs to be placed "on the line above and on the line below the code" :).
> 
> The target language is a bit complicated thing - each language provider can use different "language code", that's why it didn't worked well when switching between providers. But in the new version I've updated the DeepL language support (which added some new languages) and they seems to be using different format now, more compatible with other translators, that's why it works now.
> 
> But yeah, there are some annoying things about my translator that needs fixing, but usually I have too much work with my other addons, mostly my big speed dial (that actually pays for all my other addons).

aahh now it works, thank you.

This is not really complicated: if you save e.g. language 0 in about:config as lang then you set for translator e.g. DE_DE or whatevever hardcoded in the addon :wink:

**Comment by Juraj-Masiar** [comment]
> It would be really nice if the Addon is able to recognize the last target language.

I'll see what I can do :), sounds easy enough.

**Comment by MarkyMarkDE** [comment]
> > It would be really nice if the Addon is able to recognize the last target language.
> 
> I'll see what I can do :), sounds easy enough.

Thank you so much for your Work! Other Addon Authors didn't that in the same way, they say "sorry, we must wait for fixing of the API for deepl, there is nothing what i can do".

**Comment by Juraj-Masiar** [comment]
Well, people are busy, and workarounds are often hard to do, so understandable. 
And considering people do this for free, you can't expect much :)

**Comment by MarkyMarkDE** [comment]
> Well, people are busy, and workarounds are often hard to do, so understandable. And considering people do this for free, you can't expect much :)

I expect that the Addon will work in the described way, and if this Addon has only one function and this do not work, can't be the solution to piss of the user! Right? :wink: By the way: sometimes 4.9 in Firefox didn't work with deepl (same problem then previous in TB), can you take a look on it here?

**Comment by Juraj-Masiar** [comment]
Are you sure it happens in Firefox too? I can't reproduce it here.
How is the translator opened in your Firefox when you use context menu? Is it in the popup, modal or new window?
When you see it next time, please write here exact steps you did and ideally add a screenshot too :).

**Comment by MarkyMarkDE** [comment]
> Are you sure it happens in Firefox too? I can't reproduce it here. How is the translator opened in your Firefox when you use context menu? Is it in the popup, modal or new window? When you see it next time, please write here exact steps you did and ideally add a screenshot too :).

this sometimes happens here on GitHub. I write out of memory a answer in english and thenI like to check my grammar with deepl, then the "NEW WINDOW" opend via context menu opens a blank window. Then i close it again and reopened and all is fine.

**Comment by Juraj-Masiar** [comment]
No problem :), I'm happy you like it! And I like it too! I should have done it long ago.

**Comment by MarkyMarkDE** [comment]
> No problem :), I'm happy you like it! And I like it too! I should have done it long ago.

I really thank you so much and I appreciate your work.
Yes, I like your Addon really much, also that i can use the same looking Addon from the Same Author in TB and FF too.
When I can do something for you, let me know :wink:.

By the way: who do you save the current settings of your Addon?
Have checked the `about:config` but nothing to find, looked in the Addon, and also no database in there ...

**Comment by Juraj-Masiar** [comment]
Regarding the storage - modern addons doesn't have access to "about:config", nor the drive or any files stored in your PC.
They need to use special API that tell browser to store (or load) data and browser will "somehow" store (or load) the data.
So data stored in this addon are stored using "browser.storage.local" API which is then in Firefox stored in some SQLLight
