### ISSUE TITLE
Thunderbird 102.15.0: Deepl didin't work again

### ISSUE THREAD

**Issue by MarkyMarkDE** [fastaddons/WebTranslate#15]
In Thunderbird 102.15.0 released yesterday, it seems that Deepl didn't work again, same behavior as
[#14](https://github.com/fastaddons/WebTranslate/issues/14)

**Comment by MarkyMarkDE** [comment]
funny, sometimes it works and some not. Seems that the detection of the source language fails in some cases

**Comment by MarkyMarkDE** [comment]
Funny, sometimes it works and some not. Seems that the detection of the source language fails in some cases

**Comment by Juraj-Masiar** [comment]
Just to clarify, the translator will load, only the text input is empty, correct?

**Comment by MarkyMarkDE** [comment]
> Just to clarify, the translator will load, only the text input is empty, correct?

in this case it is little specific: the left hand text box is filled "Auto language Detect" but the right box stills empty. First i change left to e.g. english the right box will be updates with the tranlated text

**Comment by Juraj-Masiar** [comment]
Please make a screenshot next time you see it :)
I'll see if I can reproduce it too because I think I've seen it some time ago.

**Comment by MarkyMarkDE** [comment]
> Please make a screenshot next time you see it :) I'll see if I can reproduce it too because I think I've seen it some time ago.

yes, sure i will do this if i see it again.

**Comment by MarkyMarkDE** [comment]
> Please make a screenshot next time you see it :) I'll see if I can reproduce it too because I think I've seen it some time ago.

as you can see

![Bildschirmfoto vom 2023-09-02 14-33-27](https://github.com/fastaddons/WebTranslate/assets/12845477/ab7542ab-9fd5-4c92-a0c3-11fc7ccfaf89)

**Comment by Juraj-Masiar** [comment]
The DeepL should work as expected now.
