### ISSUE TITLE
Problems using with Thunderbird 78.7 and Mac 10.14.6 Mohave

### ISSUE THREAD

**Issue by Tko-Jim** [fastaddons/WebTranslate#4]
I love how this add-on works in Thunderbird. Very quick and easy. Unfortunately, it stopped working with Thunderbird 78 with Mac OS Mohave. The window opens but appears open only momentarily. It still works fine with Mac OS Catalina.

It initially worked with Mohave. This issue began after updating Thunderbird, but can't remember which update. The attachment has a short movie. Unfortunately upgrading one machine to Catalina is not feasible.

https://user-images.githubusercontent.com/78089345/105999646-4707a400-60f1-11eb-8f6f-69e711f9878e.mov

**Comment by fastaddons** [comment]
Hello,
Thank you for the video.
This looks like some Thunderbird issue. Could you try to install some other addon that has a pop-up window?
For example this DeepL translator:
https://addons.thunderbird.net/en-US/thunderbird/addon/deepl-selected-text/

Or my scrolling addon:
https://addons.thunderbird.net/en-US/thunderbird/addon/scroll_anywhere/

Can you open popup for these?
If yes, then try to reinstall my addon - but make sure to completely close Thunderbird after uninstalling (right click on the icon and click "Exit" or "Kill" or something like that).

**Comment by Tko-Jim** [comment]
DeepL translator worked fine with a pop-up window. After that, I removed and reinstalled web translate, Quitting Thunderbird each time. The first attempt was not successful, but on the 2nd attempt, it began to work again. Thank you for your time.  your add-on is very useful to me. I will make a donation this weekend after I finish my current project.

**Comment by fastaddons** [comment]
No problem, I'm happy it worked!
Donations are always welcomed :), thank you for supporting my work!
