### ISSUE TITLE
No pop-up showing on Thunderbird 78.7.1

### ISSUE THREAD

**Issue by smartiesxz** [fastaddons/WebTranslate#5]
Hi, I am trying to use this but no pop-up is showing after I select some text and click translate.
I enabled pop-ups in thunderbird etc.
Does this work with 78.7 ?

**Comment by fastaddons** [comment]
Hello,
Are you using Mac or Linux?
Please check also this issue: https://github.com/fastaddons/WebTranslate/issues/4

There is some problem in Thunderbird and some addons seems to got broken after upgrade. But reinstalling should help. Note that you have to restart Thunderbird after uninstalling.

**Comment by smartiesxz** [comment]
This is on Windows 10.
Add-on was installed now Thunderbird upgrade happened already a few days ago.
So it is not related to upgrade.
Of course I restarted numerous times etc etc.

**Comment by fastaddons** [comment]
I see, so what exactly is not working? When you click the toolbar icon directly, will it open?
Or is this affecting only the selected text / context menu?

**Comment by smartiesxz** [comment]
There doesn't seem to be a toolbar icon at all.
The add-on is installed and active. 
The selected text/context menu appears.
But I cannot see any toolbar icon.

**Comment by smartiesxz** [comment]
When I click on toolbar icon it pops up a window with google translate in it.
But the google translate field is empty and nothing gets translated.

**Comment by fastaddons** [comment]
So the toolbar icon works now, right? If you somehow remove it, you should be able to get it back when right click the toolbar empty space and click "Customize Toolbar" - there you should see all available icons including addons.

Yes, clicking the toolbar will open empty Google Translate window.
Now when you can see the popup window again, it should also work with the context menu when you select the text.

**Comment by smartiesxz** [comment]
Ok I found the problem: The plug-in only works if the "mail toolbar" is visible. Then you can select and click the context menu to get a translation in a pop-up.

If the mail toolbar is hidden (my default setting), the plugin doesn't work.

Thank you!

**Comment by fastaddons** [comment]
I see, thanks for letting me know! You can change in the options page opening the translator in a new tab instead.
In the future I will try to make the translation window inline - directly in the page just like it works in Firefox version.

**Comment by smartiesxz** [comment]
Thanks! The plugin doesn't seem to have any options page.

**Comment by fastaddons** [comment]
The Options page is integrated in the popup window. In there in the left menu:
![Screenshot 2021-02-16 10 43 03](https://user-images.githubusercontent.com/55486931/108045523-d98dca00-7043-11eb-987a-5fe3e3c0b74e.png)

**Comment by fastaddons** [comment]
Yes, it's actually a Settings page, not options page :), I'm sorry for the confusion.
